name: Auto merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Auto-merge a PR by dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        run: gh pr merge --auto --merge "$PR_URL" || gh pr merge --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_DEPENDABOT_TOKEN || secrets.GITHUB_TOKEN }}
